name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./ordermanagement/pom.xml
          mvn clean package -f ./deliverymatching/pom.xml
          mvn clean package -f ./payment-processing/pom.xml
          mvn clean package -f ./review-management/pom.xml
          mvn clean package -f ./eventcollection/pom.xml

      - name: Docker Build and push for Ordermanagement
        uses: docker/build-push-action@v4
        with:
          context: ./ordermanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ordermanagement:latest
            ghcr.io/${{ github.repository }}/ordermanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for Deliverymatching
        uses: docker/build-push-action@v4
        with:
          context: ./deliverymatching
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/deliverymatching:latest
            ghcr.io/${{ github.repository }}/deliverymatching:${{ github.ref_name }}
            
      - name: Docker Build and push for PaymentProcessing
        uses: docker/build-push-action@v4
        with:
          context: ./payment-processing
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/payment-processing:latest
            ghcr.io/${{ github.repository }}/payment-processing:${{ github.ref_name }}
            
      - name: Docker Build and push for ReviewManagement
        uses: docker/build-push-action@v4
        with:
          context: ./review-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/review-management:latest
            ghcr.io/${{ github.repository }}/review-management:${{ github.ref_name }}
            
      - name: Docker Build and push for Eventcollection
        uses: docker/build-push-action@v4
        with:
          context: ./eventcollection
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/eventcollection:latest
            ghcr.io/${{ github.repository }}/eventcollection:${{ github.ref_name }}
            
