---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordermanagement
  labels:
    app: ordermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordermanagement
  template:
    metadata:
      labels:
        app: ordermanagement
    spec:
      containers:
        - name: ordermanagement
          image: username/ordermanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverymatching
  labels:
    app: deliverymatching
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliverymatching
  template:
    metadata:
      labels:
        app: deliverymatching
    spec:
      containers:
        - name: deliverymatching
          image: username/deliverymatching:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processing
  labels:
    app: payment-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processing
  template:
    metadata:
      labels:
        app: payment-processing
    spec:
      containers:
        - name: payment-processing
          image: username/payment-processing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-management
  labels:
    app: review-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-management
  template:
    metadata:
      labels:
        app: review-management
    spec:
      containers:
        - name: review-management
          image: username/review-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventcollection
  labels:
    app: eventcollection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventcollection
  template:
    metadata:
      labels:
        app: eventcollection
    spec:
      containers:
        - name: eventcollection
          image: username/eventcollection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: ordermanagement
  labels:
    app: ordermanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ordermanagement


---


apiVersion: v1
kind: Service
metadata:
  name: deliverymatching
  labels:
    app: deliverymatching
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: deliverymatching


---


apiVersion: v1
kind: Service
metadata:
  name: payment-processing
  labels:
    app: payment-processing
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: payment-processing


---


apiVersion: v1
kind: Service
metadata:
  name: review-management
  labels:
    app: review-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: review-management


---


apiVersion: v1
kind: Service
metadata:
  name: eventcollection
  labels:
    app: eventcollection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: eventcollection

