apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverymatching
  labels:
    app: deliverymatching
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliverymatching
  template:
    metadata:
      labels:
        app: deliverymatching
    spec:
      containers:
        - name: deliverymatching
          image: "username/deliverymatching:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
